apiVersion: v2
name: pagopagpdingestionmanager
description: Microservice to tokenize eventhub msg
type: application
version: 0.38.0
appVersion: 0.5.6
dependencies:
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
