apiVersion: v2
name: pagopagpdingestionmanager
description: Microservice to tokenize eventhub msg
type: application
version: 0.37.0
appVersion: 0.5.4-2-PAGOPA-3337
dependencies:
  - name: microservice-chart
    version: 7.5.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
